import "./globals.css";
import Layout from "@/layout/Layout";
import { yekan } from "@/utiles/fonts";
import NextAuthProvider from "src/providers/NextAuthProvider";

export const metadata = {
  title: "main page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>
          <Layout>{children}</Layout>
        </NextAuthProvider>
      </body>
    </html>
  );
}
